version: "3.7"

networks:
  backend:
    external: false

services:
  # -------------------------------------------------
  # Application Broker
  # -------------------------------------------------
  broker:
    image: rabbitmq:3.8.3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672 # URL: http://localhost:15672 , Username: guest , Password: guest
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  # -------------------------------------------------
  # Application Backend Databases
  # -------------------------------------------------
  orders_db:
    image: postgres:12.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=orders
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  payments_db:
    image: bitnami/postgresql:12
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=payments
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
