spring:
  cloud:
    schema-registry-client:
      cached: true
    stream:
      bindings:
        paymentReceivedChannel: # [MessageChannel]
          contentType: 'application/*+avro'
          destination: payment-received
        paymentRequestedChannel: # [SubscribableChannel]
          contentType: 'application/*+avro'
      rabbit:
        bindings:
          paymentRequestedChannel:
            consumer:
              autoBindDlq: true # Enable Dead Letter Queue on [SubscribableChannel]
  datasource:
    url: jdbc:postgresql://localhost:5433/payments
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8081
