spring:
  cloud:
    schema-registry-client:
      cached: true
    stream:
      bindings:
        paymentReceivedChannel: # [MessageChannel]
          contentType: 'application/*+avro'
          destination: paymentReceivedChannel
        paymentRequestedChannel: # [SubscribableChannel]
          contentType: 'application/*+avro'
  datasource:
    url: jdbc:postgresql://localhost:5433/payments
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8081
