spring:
  cloud:
    schema-registry-client:
      cached: true
    stream:
      bindings:
        paymentRequested: # your input sink channel name [SubscribableChannel]
          contentType: 'application/*+avro'
          destination: requestPayment
          group: oms
        paymentReceived: # your output sink channel name [MessageChannel]
          contentType: 'application/*+avro'
          group: oms
  datasource:
    url: jdbc:postgresql://localhost:5433/payments
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8081
