spring:
  cloud:
    schema-registry-client:
      cached: true
    stream:
      bindings:
        input: # your input sink channel name [SubscribableChannel]
          contentType: 'application/*+avro'
          destination: input
          group: orders
        createOrder: # your output sink channel name [MessageChannel]
          contentType: 'application/*+avro'
          group: orders
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: user
    password: password
