spring:
  cloud:
    stream:
      bindings:
        paymentRequested: # your output sink channel name [MessageChannel]
          contentType: 'application/*+avro'
          group: oms
        paymentReceived: # your input sink channel name [SubscribableChannel]
          contentType: 'application/*+avro'
          destination: paymentReceived
          group: oms
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8080
