spring:
  cloud:
    stream:
      bindings:
        input: # your input sink channel name [SubscribableChannel]
          contentType: 'application/*+avro'
          destination: input
          group: order-service
        requestPayment: # your output sink channel name [MessageChannel]
          contentType: 'application/*+avro'
          group: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: user
    password: password
server:
  port: 8080
