spring:
  cloud:
    stream:
      bindings:
        paymentRequestedChannel: # [MessageChannel]
          contentType: 'application/*+avro'
          destination: paymentRequestedChannel
        paymentReceivedChannel: # [SubscribableChannel]
          contentType: 'application/*+avro'
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8080
