spring:
  cloud:
    stream:
      bindings:
        paymentRequestedChannel: # [MessageChannel]
          contentType: 'application/*+avro'
          destination: payment-requests
        paymentReceivedChannel: # [SubscribableChannel]
          contentType: 'application/*+avro'
      rabbit:
        bindings:
          paymentReceivedChannel:
            consumer:
              autoBindDlq: true # Enable Dead Letter Queue on [SubscribableChannel]
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8080
